/**
 * Schema QA report — generates a per-page JSON-LD audit for the live URLs
 * that emit dynamic schema (homepage carousel ItemList, /testimonials, etc.).
 *
 * For each tracked page we:
 *   1. Read the source file(s) that emit schema for that route.
 *   2. Extract every `@type` referenced.
 *   3. Verify required fields per type (Review, ItemList, FAQPage, Product).
 *   4. Flag obvious red flags — e.g. publisher: Google emitted on a non-Google
 *      review, ItemList without itemListElement, Review without reviewRating.
 *
 * Output: docs/64-SCHEMA-QA-PER-PAGE-REPORT.md (markdown table per page).
 *
 * This complements scripts/schema-validate.ts which is a static-source scan,
 * and scripts/schema-snapshot.ts which fetches the live URL and diffs.
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const ROOT = process.cwd();

interface Issue {
  level: "error" | "warn";
  msg: string;
}
interface PageReport {
  route: string;
  source: string[];
  types: string[];
  reviewCount: number;
  googleReviewCount: number;
  personalReviewCount: number;
  issues: Issue[];
}

const reports: PageReport[] = [];

// ---------- Page 1: Homepage carousel (ItemList of Reviews) ----------
{
  const carousel = readFileSync(join(ROOT, "src/components/TestimonialsCarousel.tsx"), "utf8");
  const data = readFileSync(join(ROOT, "src/data/testimonials.ts"), "utf8");
  const issues: Issue[] = [];

  if (!/"@type":\s*"ItemList"/.test(carousel)) issues.push({ level: "error", msg: "ItemList @type not found" });
  if (!/itemListElement/.test(carousel)) issues.push({ level: "error", msg: "ItemList missing itemListElement[]" });
  if (!/"@type":\s*"Review"/.test(carousel)) issues.push({ level: "error", msg: "Review @type not found" });
  if (!/reviewRating/.test(carousel)) issues.push({ level: "error", msg: "Review missing reviewRating" });
  if (!/itemReviewed/.test(carousel)) issues.push({ level: "error", msg: "Review missing itemReviewed (DanceSchool)" });

  // Check publisher: Google is only emitted when platform === 'google'.
  if (/publisher.*Google/.test(carousel) && !/platform === ["']google["']/.test(carousel)) {
    issues.push({ level: "error", msg: "publisher:Google emitted unconditionally — must be gated on platform === 'google'" });
  }

  // Count platforms in source data.
  const googleMatches = data.match(/platform:\s*"google"/g) || [];
  const personalMatches = data.match(/platform:\s*"personal"/g) || [];
  const total = googleMatches.length + personalMatches.length;

  // Warn if google count looks inflated relative to verifiable reviews.
  if (googleMatches.length > 0 && !/source_url/i.test(data)) {
    // Can't verify in static data file — Wix-side data has source_url.
    // No-op warning — covered by DB validation trigger.
  }

  reports.push({
    route: "/ (homepage TestimonialsCarousel)",
    source: ["src/components/TestimonialsCarousel.tsx", "src/data/testimonials.ts"],
    types: ["ItemList", "Review", "DanceSchool", "Person", "Organization (Google, conditional)"],
    reviewCount: total,
    googleReviewCount: googleMatches.length,
    personalReviewCount: personalMatches.length,
    issues,
  });
}

// ---------- Page 2: /testimonials ----------
{
  const page = readFileSync(join(ROOT, "src/pages/Testimonials.tsx"), "utf8");
  const issues: Issue[] = [];

  if (!/SeoHead/.test(page)) issues.push({ level: "error", msg: "SeoHead not used — page-level schema missing" });
  if (!/FAQPage|mainEntity/.test(page)) issues.push({ level: "warn", msg: "No FAQPage schema detected on /testimonials" });
  if (/publisher.*Google/.test(page) && !/platform === ["']google["']/.test(page)) {
    issues.push({ level: "error", msg: "publisher:Google emitted unconditionally on /testimonials" });
  }

  reports.push({
    route: "/testimonials",
    source: ["src/pages/Testimonials.tsx"],
    types: ["DanceSchool (sitewide)", "BreadcrumbList (auto)", "ItemList (carousel)", "FAQPage (if present)"],
    reviewCount: 0,
    googleReviewCount: 0,
    personalReviewCount: 0,
    issues,
  });
}

// ---------- Render ----------
const date = new Date().toISOString().split("T")[0];
const out: string[] = [];
out.push(`# Schema QA — Per-Page Report (${date})`);
out.push("");
out.push("Generated by `bun scripts/schema-qa-report.ts`. Runs in `prebuild`.");
out.push("");

let totalErrors = 0;
let totalWarns = 0;
for (const r of reports) {
  out.push(`## ${r.route}`);
  out.push("");
  out.push(`- **Source files**: ${r.source.map((s) => `\`${s}\``).join(", ")}`);
  out.push(`- **Schema @types emitted**: ${r.types.map((t) => `\`${t}\``).join(", ")}`);
  if (r.reviewCount > 0) {
    out.push(`- **Review counts**: ${r.reviewCount} total — ${r.googleReviewCount} Google, ${r.personalReviewCount} personal stories`);
  }
  out.push("");
  if (r.issues.length === 0) {
    out.push("✅ No issues detected.");
  } else {
    for (const i of r.issues) {
      out.push(`- ${i.level === "error" ? "❌" : "⚠️"} **${i.level.toUpperCase()}**: ${i.msg}`);
      if (i.level === "error") totalErrors++;
      else totalWarns++;
    }
  }
  out.push("");
}

out.push("---");
out.push("");
out.push(`**Totals**: ${totalErrors} errors, ${totalWarns} warnings across ${reports.length} pages.`);
out.push("");
out.push("Validate live JSON-LD with the Rich Results Test:");
out.push("- https://search.google.com/test/rich-results?url=https://www.puranights.com/");
out.push("- https://search.google.com/test/rich-results?url=https://www.puranights.com/testimonials");

mkdirSync(join(ROOT, "docs"), { recursive: true });
writeFileSync(join(ROOT, "docs/64-SCHEMA-QA-PER-PAGE-REPORT.md"), out.join("\n") + "\n");
console.log(`✓ Schema QA per-page report → docs/64-SCHEMA-QA-PER-PAGE-REPORT.md`);
console.log(`  errors: ${totalErrors}, warnings: ${totalWarns}`);
if (totalErrors > 0 && process.env.CI === "true") process.exit(1);
